---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.17.44

  client_rb:
    environment: "test-kitchen"
  
platforms:
  - name: ubuntu-16.04

suites:
  - name: default # master
    run_list:
      - recipe[tec-kubernetes::master]

        #  - name: pod01
        #    run_list:
        #      - recipe[tec-kubernetes::pod]
